xcodeproj: PontoConcrete.xcodeproj
workspace: PontoConcrete.xcworkspace
source_directory: PontoConcrete
output_directory: html
scheme: PontoConcrete
coverage_service: html
ignore:
    - Pods/*
    - PontoConcrete/SkyFloatingLabelTextField/*
