opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping

type_body_length:
  warning: 200
  error: 400

private_outlet:
  allow_private_set: true

file_length:
  warning: 400
  error: 600

force_unwrapping:
  severity: error

function_body_length:
  warning: 20
  error: 40

implicitly_unwrapped_optional:
  mode: all
  severity: error

disabled_rules:
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - MatchPointTests
